
//----------------------------------------------------
// The following code was generated by CUP v0.11b beta 20140220
// Wed Sep 10 10:54:29 ART 2014
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int GTEQ = 41;
  public static final int STRING_LITERAL = 17;
  public static final int MULT = 35;
  public static final int LTEQ = 40;
  public static final int LPAREN = 25;
  public static final int CONTINUE = 6;
  public static final int INT = 2;
  public static final int FOR = 9;
  public static final int MINUS = 32;
  public static final int RPAREN = 26;
  public static final int OROR = 45;
  public static final int BOOLEAN_LITERAL = 19;
  public static final int NOT = 33;
  public static final int SEMICOLON = 24;
  public static final int LT = 38;
  public static final int COMMA = 28;
  public static final int CLASS = 5;
  public static final int ANDAND = 44;
  public static final int DIV = 36;
  public static final int PLUSEQ = 29;
  public static final int MINUSEQ = 30;
  public static final int PLUS = 34;
  public static final int IF = 7;
  public static final int ID = 15;
  public static final int EOF = 0;
  public static final int RETURN = 11;
  public static final int TRUE = 13;
  public static final int error = 1;
  public static final int EQEQ = 42;
  public static final int MOD = 37;
  public static final int BREAK = 4;
  public static final int VOID = 12;
  public static final int EXTERNINVK = 31;
  public static final int EQ = 27;
  public static final int LBRACK = 22;
  public static final int LBRACE = 20;
  public static final int ELSE = 8;
  public static final int RBRACK = 23;
  public static final int WHILE = 10;
  public static final int FLOAT = 3;
  public static final int RBRACE = 21;
  public static final int FLOAT_LITERAL = 18;
  public static final int FALSE = 14;
  public static final int GT = 39;
  public static final int NOTEQ = 43;
  public static final int INT_LITERAL = 16;
}

